version: "3.9"
services:
  backend:
    env_file:
      - .env
    container_name: backend
    restart: always
    build: .
    ports:
      - "9000:9000"
  postgres:
    container_name: database
    image: postgres:13.3
    restart: always
    env_file:
      - .env 
    environment:
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASS}"
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: